server:
  port: 9000

spring:
  application:
    name: authorization-server

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
